# Generated by Django 5.0.6 on 2024-07-01 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('negocio', '0002_libro_usuario_delete_usuarios'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='libro',
            options={'ordering': ['titulo', 'autor']},
        ),
        migrations.AlterModelOptions(
            name='proveedor',
            options={'verbose_name': 'Proveedor', 'verbose_name_plural': 'Proveedores'},
        ),
    ]
