# Generated by Django 5.0.6 on 2024-07-01 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('negocio', '0003_alter_libro_options_alter_proveedor_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='año',
            new_name='ano',
        ),
    ]
