# Generated by Django 5.0.6 on 2024-07-01 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('negocio', '0004_rename_año_libro_ano'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='ano',
            new_name='anio',
        ),
    ]
